# Plot title
title: HPCG Benchmark

# Axes must have a value specified with a perflog column name or a
# benchmark parameter name (denoted by a "%" in the perflog "info"
# and "display_name" fields, if it exists).
# Units can either be specified with a perflog column name
# or a custom label (including null (i.e. None) if units are N/A).

x_axis:
  value: "test_name"
  units:
    custom: null

y_axis:
  value: "flops_value"
  units:
    column: "flops_unit"
  scaling:
    column:
      name: "flops_value"
      x_value: "HPCG_Original"

# Optional row filters (specify an empty list [] if none are required).
# Filter format: [column_name, operator, value]
filters:
  and: [["test_name", "!=", "HPCG_IntelSKX_Isambard"], ["test_name", "!=", "HPCG_IntelAVX_Isambard"]]
  or: []

# Optional setting to display several plots in the same graph.
# Number of series, if used, must be >=2 (specify an empty list [] if there is only one series).
# Do not use more than two distinct column names in this list -
# bokeh can only handle 3 x-axis groups (2 series columns + 1 x-axis column).
# NOTE: For now, only one distinct column name is supported.
# Series format: [column_name, value]
series: [["system", "archer2"], ["system", "isambard-macs"]]

# All columns used in axes, filters, and series must have a user-specified type.
# Type refers to the pandas dtype each column should be interpreted as
# (e.g. str/string/object, int/int64, float/float64, datetime/datetime64).
column_types:
  test_name: "str"
  flops_value: "float"
  flops_unit: "str"
  system: "str"
