# Plot title
title: "Example Plot"

# Optional row filters (specify an empty list [] if none are required)
# Filtering may be conducted on columns that are not specified
# in the list of columns above (so that the column is filtered by but also dropped)
# Filter format: [column_name, operator, value]
filters: [["system", "==", "default"]]

# Optional setting to display several plots in the same graph
# Number of datasets, if used, must be >=2 (specify an empty list [] if there is only one dataset)
# Dataset format: [column_name, value]
datasets: [["cpus_per_task", "1"], ["cpus_per_task", "2"]]

# Axes must have a value specified with a column name
# Units can either be specified with a column name
# or a custom label (including null (i.e. None) if units are N/A)

x_axis:
  value: "tasks"
  units:
    custom: null

y_axis:
  value: "flops_value"
  units:
    column: "flops_unit"
