title: "Performance vs number of tasks and CPUs_per_task"

x_axis:
  value: "tasks"
  units:
    custom: null

y_axis:
  value: "flops_value"
  units:
    column: "flops_unit"

filters: [["tags", "==", "example"]]

series: [["cpus_per_task", "1"], ["cpus_per_task", "2"]]
