# Plot title
title: "Example Plot"

# Axes must have a value specified with a column name
# Units can either be specified with a column name
# or a custom label (including null (i.e. None) if units are N/A)

x_axis:
  value: "tasks"
  units:
    custom: null

y_axis:
  value: "flops_value"
  units:
    column: "flops_unit"

# Optional row filters (specify an empty list [] if none are required)
# Filtering may be conducted on columns that are not specified
# in the list of columns above (so that the column is filtered by but also dropped)
# Filter format: [column_name, operator, value]
filters: [["system", "==", "default"]]

# Optional setting to display several plots in the same graph
# Number of series, if used, must be >=2 (specify an empty list [] if there is only one series)
# Do not use more than two distinct columns in this list -
# bokeh can only handle 3 x-axis groups (2 series columns + 1 x-axis column)
# Series format: [column_name, value]
series: [["cpus_per_task", "1"], ["cpus_per_task", "2"]]
