name: Publish docs preview via GitHub Pages
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Add config options
        run: |
          echo "site_url: https://ukri-excalibur.github.io/excalibur-tests/preview" >> ./mkdocs.yml
          echo "remote_branch: gh-preview" >> ./mkdocs.yml

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: ./mkdocs.yml
