name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Deploy docs
        if: ${{ github.event_name == 'push' }}
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: ./mkdocs.yml

      - name: Deploy docs to preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: ./mkdocs.yml
          MKDOCS_SITE_URL: https://ukri-excalibur.github.io/excalibur-tests/preview
          MKDOCS_REMOTE_BRANCH: gh-preview
